# Generated by Django 5.0.4 on 2024-04-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimpleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char_field", models.CharField(max_length=255)),
                ("date", models.DateField(auto_now_add=True)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("boolean", models.BooleanField(default=False)),
            ],
        ),
    ]
