name: Codeartifact
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: Gr1N/setup-poetry@v8
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.ROLE }}

      - name: Configure poetry
        run: |
          export CODEARTIFACT_REPOSITORY_URL=`aws codeartifact get-repository-endpoint --domain ${{ secrets.CODEARTIFACT_DOMAIN }} --domain-owner ${{ secrets.CODEARTIFACT_DOMAIN_OWNER }} --repository ${{ secrets.CODEARTIFACT_REPOSITORY }} --format pypi --query repositoryEndpoint --output text`
          export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain ${{ secrets.CODEARTIFACT_DOMAIN }} --domain-owner ${{ secrets.CODEARTIFACT_DOMAIN_OWNER }} --query authorizationToken --output text`
          poetry config repositories.codeartifact $CODEARTIFACT_REPOSITORY_URL
          poetry config http-basic.codeartifact aws $CODEARTIFACT_AUTH_TOKEN

      - name: Build package
        run: poetry build

      - name: Push Package
        run: poetry publish -r codeartifact
